version: '3'

services:
  questions-db:
    image: "mvertes/alpine-mongo:4.0.5-0"
  notifications-db:
    image: "mvertes/alpine-mongo:4.0.5-0"
  users-db:
    image: "mvertes/alpine-mongo:4.0.5-0"
  notifications-mq:
    image: "rabbitmq:3.7-alpine"
  emails-mq:
    image: "rabbitmq:3.7-alpine"
  smtp:
    build: ./smtp
    ports:
     - "1080:1080"

  app:
    build: ./app

  notifications:
    build: ./notifications
    environment:
      MONGODB_URL: mongodb://notifications-db:27017/questions
      INBOUND_AMQP_URL: amqp://notifications-mq:5672
      OUTBOUND_AMQP_URL: amqp://emails-mq:5672
      WAIT_HOSTS: notifications-db:27017, notifications-mq:5672, emails-mq:5672
      WAIT_HOSTS_TIMEOUT: 120
    links:
     - emails-mq
     - notifications-mq
     - notifications-db

  questions:
    build: ./questions
    environment:
      MONGODB_URL: mongodb://questions-db:27017/questions
      AMQP_URL: amqp://notifications-mq:5672
      WAIT_HOSTS: questions-db:27017, notifications-mq:5672
      WAIT_HOSTS_TIMEOUT: 120
    links:
     - questions-db
     - notifications-mq
  
  emails:
    build: ./emails
    environment:
      AMQP_URL: amqp://emails-mq:5672
      SMTP_HOST: smtp
      SMTP_PORT: 1025
      SMTP_USER: test
      SMTP_PASSWORD: test
      SMTP_SENDER: test@example.com
      WAIT_HOSTS: smtp:1025, emails-mq:5672
      WAIT_HOSTS_TIMEOUT: 120
    links:
     - smtp
     - emails-mq

  users:
    build: ./users
    environment:
      AMQP_URL: amqp://emails-mq:5672
      MONGODB_URL: mongodb://users-db:27017/questions
      REGISTRATION_BASE_URL: ${UI_BASE_URL}#/activate/
      JWT_KEY: ${JWT_KEY}
      OAUTH_CLIENT: ${OAUTH_CLIENT}
      OAUTH_SECRET: ${OAUTH_SECRET}
      WAIT_HOSTS: emails-mq:5672, users-db:27017
      WAIT_HOSTS_TIMEOUT: 120
    links:
     - emails-mq
     - users-db

  gateway:
    build: ./gateway
    ports:
     - "443:8080"
    environment:
      ZUUL_ROUTES_UI_URL: http://app
      ZUUL_ROUTES_OAUTH_URL: http://users:3000/oauth
      ZUUL_ROUTES_USERS_URL: http://users:3000/users
      ZUUL_ROUTES_QUESTIONS_URL: http://questions:3000/questions
      ZUUL_ROUTES_NOTIFICATIONS_URL: http://notifications:3000
      OAUTH_CLIENT: ${OAUTH_CLIENT}
      OAUTH_SECRET: ${OAUTH_SECRET}
      OAUTH_KEY: ${JWT_KEY}
      WAIT_HOSTS: notifications:3000, questions:3000, users:3000, app:80
      WAIT_HOSTS_TIMEOUT: 120
    links:
     - notifications
     - questions
     - users
